export const componentCite:  Record<string,any> = {
  alert: {
    component: "Alert",
    componentCode: "alert",
    cite: "Then they were informed, then they were messaged, then they were alerted.",
    author: "Br Jhons, 1752",
  },
  avatar: {
    component: "Avatar",
    componentCode: "avatar",
    cite: "If it's not you, then it's the other you",
    author: "A. Render, 1995",
  },
  button: {
    component: "Button",
    componentCode: "button",
    cite: "There were a place where we used to click. You've called it a button, and we clicked yes. R. Falgt, 1354",
    author: "R. Falgt, 1354",
  },
  tabs: {
    component: "Tabs",
    componentCode: "tabs",
    cite: "A journey of a thousand pages begins with a single tab",
    author: "Confucius, 450 BC",
  },
  box: {
    component: "Box",
    componentCode: "box",
    cite: "Boxes, essentially, contain other boxes. That's the meaning we'll find if we open them .",
    author: "B. Franklin, 1854",
  },
  backdrop: {
    component: "Backdrop",
    componentCode: "backdrop",
    cite: "The background, the stage, the curtain: it's all a backdrop",
    author: "P. Shaw, 1900",
  },
  cartouche: {
    component: "Cartouche",
    componentCode: "cartouche",
    cite: "Open up', they said. So we stackedG.",
    author: "G. Brahms, 1964",
  },
  chip: {
    component: "Chip",
    componentCode: "chip",
    cite: "Small bits of information, always at hand",
    author: "J. Chips, 1985",
  },
  column: {
    component: "Column",
    componentCode: "column",
    cite: "What else? Cells? We are columns",
    author: "D. Viesas, 1964",
  },
  divider: {
    component: "Divider",
    componentCode: "divider",
    cite: "What is separating before from after is not a time nor a place : it's only a component",
    author: "B. Franklin, 1854",
  },
  drawer: {
    component: "Drawer",
    componentCode: "drawer",
    cite: "The hidden compartment, always there when needed",
    author: "M. Drawer, 2005",
  },
  list: {
    component: "List",
    componentCode: "list",
    cite: "List differs from menu essentially by the way you call it",
    author: "R. List, 1990",
  },
  progress: {
    component: "Progress",
    componentCode: "progress",
    cite: "You'll never know that you've got a score, unless comes the day when you see the other's ones.",
    author: "S. Roch, 1824",
  },
  slider: {
    component: "Slider",
    componentCode: "slider",
    cite: "Adjusting the flow, one step at a time",
    author: "L. Slider, 2010",
  },
  autoComplete: {
    component: "AutoComplete",
    componentCode: "autoComplete",
    cite: "Completing the journey together, hand in hand with Autocomplete.",
    author: "J. Keats, 1820",
  },
  dataList: {
    component: "DataList",
    componentCode: "dataList",
    cite: "Those who call them tables are the same who name stones as chairs. Reality is above : datalist is a datalist table .",
    author: "A. Einstein, 1879",
  },
  finder: {
    component: "Finder",
    componentCode: "finder",
    cite: "This constant need about knowing what I was looking for, this need, I gave it a name.",
    author: "H. Maifield, 1996",
  },
  grouper: {
    component: "Grouper",
    componentCode: "grouper",
    cite: "Together we stand, divided we fall. The importance of grouping.",
    author: "A. Lincoln, 1863",
  },
  loader: {
    component: "Loader",
    componentCode: "loader",
    cite: "And suddenly, in this dark cabinet, I realized that the most pleasant phase was that of waiting.",
    author: "D. Pentes, 824",
  },
  sorter: {
    component: "Sorter",
    componentCode: "sorter",
    cite: "Then, what was before became the after.",
    author: "R. Hakran, 824",
  },
  confirm: {
    component: "Confirm",
    componentCode: "confirm",
    cite: "Leaded by a proud walk, nothing can stop nobody to win the step ahead, should we confirm ?",
    author: "V.Hugo 1850",
  },
    input: {
    component: "Input",
    componentCode: "input",
    cite: "The words we type today will shape the thoughts of tomorrow",
    author: "Anonymous, 2022",
  }, 
  switch: {
    component: "Switch",
    componentCode: "switch",
    cite: "With a flick of a switch, worlds are changed and opportunities arise",
    author: "Nikola Tesla, 1894",
  },
  select: {
    component: "Select",
    componentCode: "select",
    cite: "To select or not to select, that is the question.",
    author: "Jhon. Shakespare, 1623",
  },
  frame: {
    component: "Frame",
    componentCode: "frame",
    cite: "What happens in the Frame, stays in the Frame",
    author: "R. Smith, 1452",
  },
  login: {
    component: "Login",
    componentCode: "login",
    cite: "The journey of a thousand miles begins with a single login.",
    author: "T. Lao, 568",
  },
  menu: {
    component: "Menu",
    componentCode: "menu",
    cite: "A menu is not a list, it's just like a list but more and less",
    author: "S. Kim, 1654",
  },
  panel: {
    component: "Panel",
    componentCode: "panel",
    cite: "If you can slide, then there are chances you are a panel.",
    author: "C. Quin, 2013",
  },
  popper: {
    component: "Popper",
    componentCode: "popper",
    cite: "This Popper is the base of all the flyout stuff: it pops",
    author: "P. Cheng, 1045",
  },
  toast: {
    component: "Toast",
    componentCode: "toast",
    cite: "A message in a bottle that never gets lost at sea.",
    author: "H. Chen, 756",
  },
  togglebar: {
    component: "ToggleBar",
    componentCode: "togglebar",
    cite: "Toggling between states with ease, that's what ToggleBars do best.",
    author: "Q. Jones, 954",
  },
  toolbar: {
    component: "ToolBar",
    componentCode: "toolbar",
    cite: "Way more than putting tools in a bar: having them in a toolbar!",
    author: "Q. Jones, 450",
  },
  window: {
    component: "Window",
    componentCode: "window",
    cite: "Claiming they were not doors, made what they are today: windows.",
    author: "Ch XX, 1320",
  },
};
